package com.inmo.hibernate;
// Generated 31-ene-2015 14:13:45 by Hibernate Tools 3.6.0



/**
 * Imagen generated by hbm2java
 */
public class Imagen  implements java.io.Serializable {


     private Integer idImagen;
     private Inmueble inmueble;
     private String ruta;

    public Imagen() {
    }

    public Imagen(Inmueble inmueble, String ruta) {
       this.inmueble = inmueble;
       this.ruta = ruta;
    }
   
    public Integer getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(Integer idImagen) {
        this.idImagen = idImagen;
    }
    public Inmueble getInmueble() {
        return this.inmueble;
    }
    
    public void setInmueble(Inmueble inmueble) {
        this.inmueble = inmueble;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

}


