package com.inmo.hibernate;
// Generated 31-ene-2015 14:13:45 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Inmueble generated by hbm2java
 */
public class Inmueble  implements java.io.Serializable {


     private Integer idInmbule;
     private int idAndroid;
     private String localidad;
     private String direccion;
     private String tipo;
     private String precio;
     private String usuario;
     private Set imagens = new HashSet(0);

    public Inmueble() {
    }

	
    public Inmueble(int idAndroid, String localidad, String direccion, String tipo, String precio, String usuario) {
        this.idAndroid = idAndroid;
        this.localidad = localidad;
        this.direccion = direccion;
        this.tipo = tipo;
        this.precio = precio;
        this.usuario = usuario;
    }
    public Inmueble(int idAndroid, String localidad, String direccion, String tipo, String precio, String usuario, Set imagens) {
       this.idAndroid = idAndroid;
       this.localidad = localidad;
       this.direccion = direccion;
       this.tipo = tipo;
       this.precio = precio;
       this.usuario = usuario;
       this.imagens = imagens;
    }
   
    public Integer getIdInmbule() {
        return this.idInmbule;
    }
    
    public void setIdInmbule(Integer idInmbule) {
        this.idInmbule = idInmbule;
    }
    public int getIdAndroid() {
        return this.idAndroid;
    }
    
    public void setIdAndroid(int idAndroid) {
        this.idAndroid = idAndroid;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Set getImagens() {
        return this.imagens;
    }
    
    public void setImagens(Set imagens) {
        this.imagens = imagens;
    }




}


